apiVersion: argoproj.io/v1alpha1
kind: ArgoCD
metadata:
  name: demolab-argocd
  namespace: argocd
spec:
  version: v2.0.0
  usersAnonymousEnabled: true
  ha:
    enabled: true
  dex:
    image: quay.io/redhat-cop/dex
    version: v2.22.0-openshift
    openShiftOAuth: true
  grafana:
    enabled: true
    route: 
      enabled: true
  prometheus:
    enabled: true
    route: 
      enabled: true
  rbac:
    defaultPolicy: 'role:readonly'
    policy: |
      g, system:cluster-admins, role:admin
      g, argocd-users, role:readonly
      g, argocd-admins, role:admin
      g, tektonbot, role:admin
    scopes: '[groups]'
  applicationInstanceLabelKey: paolocarta.me/argoapp
  repositories: |
    - url: https://github.com/paolocarta/ocp-gitops-cicd-pipeline.git
  server:
    enabled: true
    route: 
      enabled: true
    autoscale:
      enabled: true
      hpa:
        maxReplicas: 3
        minReplicas: 2
        scaleTargetRef:
          apiVersion: extensions/v1beta1
          kind: Deployment
          name: demolab-argocd-server
        targetCPUUtilizationPercentage: 50
  resourceExclusions: |
    - apiGroups:
      - tekton.dev
      kinds:
      - PipelineRun
      - TaskRun
      clusters:
      - "https://kubernetes.default.svc"
