kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cluster-admin-argocd
    # generateName: cluster-admin-argocd
subjects:
  - kind: ServiceAccount
    # name: argocd-application-controller
    name: demolab-argocd-argocd-application-controller
    namespace: argocd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
