apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: {{ include "springboot-tekton.fullname" . }}-tt
spec:
  params:
  - name: git-repo-url
    description: The git repository url
  - name: git-repo-ssh-url
    description: The git repository ssh url
  - name: git-commit-id
    description: The git commit sha
  - name: git-branch
    description: The git revision
    default: master
  - name: git-repo-name
    description: The name of the deployment to be created / patched
####
  resourcetemplates:
  - apiVersion: tekton.dev/v1alpha1
    kind: PipelineResource
    metadata:
      name: $(params.git-repo-name)-code-$(uid)
      annotations:
        argocd.argoproj.io/compare-options: IgnoreExtraneous
      labels:
        commit-id: $(params.git-commit-id)
    spec:
      type: git
      params:
      - name: url
        value: $(params.git-repo-ssh-url)
      - name: revision
        value: $(params.git-branch)

  - apiVersion: tekton.dev/v1alpha1
    kind: PipelineRun
    metadata:
      name: $(params.git-repo-name)-pr-$(uid)
      annotations:
        argocd.argoproj.io/compare-options: IgnoreExtraneous
      labels:
        commit-id: $(params.git-commit-id)
    spec:
      pipelineRef:
        name: {{ include "springboot-tekton.fullname" . }}-pipeline
      resources:
      - name: {{ include "springboot-tekton.fullname" . }}-source
        resourceRef:
          name: $(params.git-repo-name)-code-$(uid)
      - name: gitops-repo
        resourceRef:
          name: gitops-manifests-pipe-resource
      - name: {{ include "springboot-tekton.fullname" . }}-image
        resourceRef:
          name: {{ include "springboot-tekton.fullname" . }}-image
      serviceAccountName: {{ .Values.serviceAccount.name }}
      workspaces:
      - name: local-maven-repo
        persistentVolumeClaim:
          claimName: maven-repo-pvc-spring-rest
      - name: exchange-area
        persistentVolumeClaim:
          claimName: exchange-area-pvc-spring-rest
      timeout: 20m0s


