apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  labels:
{{ include "springboot-tekton.labels" . | nindent 4 }}
  name: maven-build
spec:
  workspaces:
  - name: maven-repo
  - name: output-area
  
  params:
    - name: GOALS
      default:
        - package
        # - -DskipTests
      description: The Maven goals to run
      type: array

  resources:
    inputs:
      - name: source
        type: git

  results:
    - name: image-tag
      description: image-tag

  steps:
  - name: package
    image: {{ .Values.maven.image.repository }}:{{ .Values.maven.image.tag }}
    workingDir: /workspace/source
    command:
    - mvn
    args:
    - -Dmaven.repo.local=$(workspaces.maven-repo.path)
    - "$(params.GOALS)"

  - name: copy-assets 
    image: quay.io/openshift-pipeline/openshift-cli:v0.8.0
    command: ["cp"]
    args:
      - /workspace/source/target/shift-rest-1.0.0-SNAPSHOT.jar
      - /workspace/output-area

  - name: copy-assets-2
    image: quay.io/openshift-pipeline/openshift-cli:v0.8.0
    command: ["cp"]
    args:
      - /workspace/source/Dockerfile
      - /workspace/output-area

  - name: new-version
    image: clamer/kikd:1.0.3
    imagePullPolicy: IfNotPresent
    workingDir: /workspace/source
    script: |
      cp -r /tekton/home/.ssh /root/.ssh
      jx-release-version | tee $(results.image-tag.path)
      git fetch --tags && jx-release-version > /workspace/output-area/version