kind: Group
apiVersion: user.openshift.io/v1
metadata:
  name: argocd-users
users: 
  - user1
  - user2
---
kind: Group
apiVersion: user.openshift.io/v1
metadata:
  name: argocd-admins
users:
  - paolocarta
  - tektonbot
  - kubeadmin
---
kind: Group
apiVersion: user.openshift.io/v1
metadata:
  name: developerteam1
users:
  - user1
  - user2